### ISSUE TITLE
Client timeout 'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')

### ISSUE THREAD

**Issue by kzzzr** [ClickHouse/dbt-clickhouse#65]
Hey, guys!

I face with an error while building dbt models. Looks like a timeout or forced socket close:

```log
root@aa7114577c23:/usr/app# dbt build -s lineorder
07:49:58  Running with dbt=1.1.1
07:49:58  Found 5 models, 10 tests, 0 snapshots, 0 analyses, 410 macros, 0 operations, 0 seed files, 4 sources, 0 exposures, 0 metrics
07:49:58  
07:49:59  Concurrency: 1 threads (target='dev')
07:49:59  
07:49:59  1 of 3 START table model default.lineorder ..................................... [RUN]
Unexpected Http Driver Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/clickhouse_connect/driver/httpclient.py", line 228, in _raw_request
    response: Response = self.session.request(method, self.url,
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
07:54:59  1 of 3 ERROR creating table model default.lineorder ............................ [ERROR in 300.27s]
07:54:59  2 of 3 SKIP test not_null_lineorder_LO_ORDERKEY ................................ [SKIP]
07:54:59  3 of 3 SKIP test unique_lineorder_LO_ORDERKEY .................................. [SKIP]
07:54:59  
07:54:59  Finished running 1 table model, 2 tests in 300.98s.
07:54:59  
07:54:59  Completed with 1 error and 0 warnings:
07:54:59  
07:54:59  Database Error in model lineorder (models/staging/lineorder.sql)
07:54:59    Error executing HTTP request https://rc1a-cjvd2g0abalacpl5.mdb.yandexcloud.net:8443
07:54:59    compiled SQL at target/run/clickhouse_starschema/models/staging/lineorder.sql
07:54:59  
07:54:59  Done. PASS=0 WARN=0 ERROR=1 SKIP=2 TOTAL=3
```

dbt-clickhouse Version: `1.1.0.2`

```
root@aa7114577c23:/usr/app# pip show dbt-clickhouse
Name: dbt-clickhouse
Version: 1.1.0.2
Summary: The Clickhouse plugin for dbt (data build tool)
Home-page: https://github.com/ClickHouse/dbt-clickhouse
```

My `profiles.yml` looks like this:

```yaml
clickhouse_starschema:
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: "{{ env_var('DBT_HOST') }}"
      port: 8443
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      secure: True
      verify: False
      send_receive_timeout: 1000
  target: dev
```

According to query log the queries I've triggered via dbt were finished on server's side successfully. Yet, client side is timed out and disconnected resulting in dbt failure.

I've also tried  applying manual setting to this particular model but this had no effect:

```
settings 
      receive_timeout=1000
    , send_timeout=1000
    , send_progress_in_http_headers=0
    , max_execution_time=1000
    , http_send_timeout=1000
    , http_receive_timeout=1000
```

**Comment by kzzzr** [comment]
> Which version of clickhouse-connect are you using?

Not sure. One that dbt-clickhouse of Version: `1.1.0.2` uses.

> In particular you might try setting the receive_timeout and send_timeouts to larger numbers in the ClickHouse default profile.

I don't think this is possible to set with Managed Clickhouse service (Y.Cloud).
However long queries used to work with previous versions (prior to HTTP request)

**Comment by genzgd** [comment]
I recreated this issue connecting to ClickHouse on AWS EC2 using a Mac.  The most recent dbt version 1.1.5 should contain the ClickHouse Connect fix (related to setting keep alive on the TCP socket used by the HTTP connection).

Please reopen if you see continued issues.  In some cases you *might* need to increase the send_receive_timeout in the dbt profile.
